// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokerLeague.DBContext;

#nullable disable

namespace PokerTournamentManager.Migrations
{
    [DbContext(typeof(PokerLeagueContext))]
    [Migration("20230601170746_addparticipants")]
    partial class addparticipants
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PokerTournamentManager.Models.League", b =>
                {
                    b.Property<int>("LeagueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LeagueId"), 1L, 1);

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("LeagueId");

                    b.ToTable("Leagues");

                    b.HasData(
                        new
                        {
                            LeagueId = 1,
                            EndTime = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueName = "Freiburg's Tavern Poker Club",
                            StartTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeagueId = 3,
                            EndTime = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueName = "Raleigh Persian Club Poker League",
                            StartTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            LeagueId = 2,
                            EndTime = new DateTime(2023, 12, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueName = "Gabe's Poker League",
                            StartTime = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PokerTournamentManager.Models.Participant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"), 1L, 1);

                    b.Property<int>("AddOnCount")
                        .HasColumnType("int");

                    b.Property<int>("BountiesWon")
                        .HasColumnType("int");

                    b.Property<int?>("FinishPosition")
                        .HasColumnType("int");

                    b.Property<bool>("IsPlayerEligibleForPrize")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("RebuyCount")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("ParticipantId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Participants");

                    b.HasData(
                        new
                        {
                            ParticipantId = 1,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 1,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 1,
                            RebuyCount = 0,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 2,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 2,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 2,
                            RebuyCount = 1,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 3,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 3,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 3,
                            RebuyCount = 1,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 4,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 4,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 4,
                            RebuyCount = 0,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 5,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 5,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 5,
                            RebuyCount = 0,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 6,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 6,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 6,
                            RebuyCount = 1,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 7,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 7,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 7,
                            RebuyCount = 1,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 8,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 8,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 8,
                            RebuyCount = 0,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 9,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 9,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 9,
                            RebuyCount = 0,
                            TournamentId = 2
                        },
                        new
                        {
                            ParticipantId = 10,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 3,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 1,
                            RebuyCount = 1,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 11,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 2,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 3,
                            RebuyCount = 1,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 12,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 1,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 4,
                            RebuyCount = 0,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 13,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 9,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 5,
                            RebuyCount = 0,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 14,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 8,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 7,
                            RebuyCount = 1,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 15,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 7,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 8,
                            RebuyCount = 1,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 16,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 4,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 9,
                            RebuyCount = 0,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 17,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 5,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 12,
                            RebuyCount = 0,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 18,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 6,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 14,
                            RebuyCount = 0,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 19,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 10,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 15,
                            RebuyCount = 0,
                            TournamentId = 3
                        },
                        new
                        {
                            ParticipantId = 20,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 1,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 11,
                            RebuyCount = 0,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 21,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 2,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 12,
                            RebuyCount = 1,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 22,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 3,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 13,
                            RebuyCount = 1,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 23,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 4,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 4,
                            RebuyCount = 0,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 24,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 5,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 15,
                            RebuyCount = 0,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 25,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 6,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 16,
                            RebuyCount = 1,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 26,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 7,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 7,
                            RebuyCount = 1,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 27,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 8,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 18,
                            RebuyCount = 0,
                            TournamentId = 4
                        },
                        new
                        {
                            ParticipantId = 28,
                            AddOnCount = 0,
                            BountiesWon = 0,
                            FinishPosition = 9,
                            IsPlayerEligibleForPrize = true,
                            PlayerId = 19,
                            RebuyCount = 0,
                            TournamentId = 4
                        });
                });

            modelBuilder.Entity("PokerTournamentManager.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PlayerId"), 1L, 1);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PlayerId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            PlayerId = 1,
                            UserName = "Saeid"
                        },
                        new
                        {
                            PlayerId = 2,
                            UserName = "Masoud"
                        },
                        new
                        {
                            PlayerId = 3,
                            UserName = "Nikolai"
                        },
                        new
                        {
                            PlayerId = 4,
                            UserName = "Michael"
                        },
                        new
                        {
                            PlayerId = 5,
                            UserName = "Silvia"
                        },
                        new
                        {
                            PlayerId = 6,
                            UserName = "Simon"
                        },
                        new
                        {
                            PlayerId = 7,
                            UserName = "Andreas"
                        },
                        new
                        {
                            PlayerId = 8,
                            UserName = "Isabela"
                        },
                        new
                        {
                            PlayerId = 9,
                            UserName = "Klaus"
                        },
                        new
                        {
                            PlayerId = 10,
                            UserName = "Eva"
                        },
                        new
                        {
                            PlayerId = 11,
                            UserName = "Vika"
                        },
                        new
                        {
                            PlayerId = 12,
                            UserName = "Majid"
                        },
                        new
                        {
                            PlayerId = 13,
                            UserName = "Sebastian"
                        },
                        new
                        {
                            PlayerId = 14,
                            UserName = "Pedram"
                        },
                        new
                        {
                            PlayerId = 15,
                            UserName = "Thomas"
                        },
                        new
                        {
                            PlayerId = 16,
                            UserName = "Kiril"
                        },
                        new
                        {
                            PlayerId = 17,
                            UserName = "Christoph"
                        },
                        new
                        {
                            PlayerId = 18,
                            UserName = "Konstantin"
                        },
                        new
                        {
                            PlayerId = 19,
                            UserName = "Mehdi"
                        });
                });

            modelBuilder.Entity("PokerTournamentManager.Models.Tournament", b =>
                {
                    b.Property<int>("TournamentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TournamentId"), 1L, 1);

                    b.Property<double>("AddOn")
                        .HasColumnType("float");

                    b.Property<double>("Bounty")
                        .HasColumnType("float");

                    b.Property<double>("BuyIn")
                        .HasColumnType("float");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<int>("MaxAddOnCount")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("Rebuy")
                        .HasColumnType("float");

                    b.Property<int>("StackSizeAddon")
                        .HasColumnType("int");

                    b.Property<int>("StackSizeRebuy")
                        .HasColumnType("int");

                    b.Property<int>("StackSizeStarting")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TournamentId");

                    b.ToTable("Tournaments");

                    b.HasData(
                        new
                        {
                            TournamentId = 1,
                            AddOn = 0.0,
                            Bounty = 0.0,
                            BuyIn = 600.0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 2,
                            MaxAddOnCount = 0,
                            MaxParticipants = 0,
                            Name = "Gabe Fenton Openning $600 No Limit Holdem",
                            Rebuy = 600.0,
                            StackSizeAddon = 0,
                            StackSizeRebuy = 0,
                            StackSizeStarting = 0,
                            StartTime = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Saeid's House"
                        },
                        new
                        {
                            TournamentId = 2,
                            AddOn = 0.0,
                            Bounty = 0.0,
                            BuyIn = 25.0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            MaxAddOnCount = 0,
                            MaxParticipants = 0,
                            Name = "Saeid #1 $25 No Limit Holdem",
                            Rebuy = 25.0,
                            StackSizeAddon = 0,
                            StackSizeRebuy = 0,
                            StackSizeStarting = 0,
                            StartTime = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Saeid's House"
                        },
                        new
                        {
                            TournamentId = 3,
                            AddOn = 0.0,
                            Bounty = 0.0,
                            BuyIn = 25.0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            MaxAddOnCount = 0,
                            MaxParticipants = 0,
                            Name = "Saeid #2 $25 No Limit Holdem",
                            Rebuy = 25.0,
                            StackSizeAddon = 0,
                            StackSizeRebuy = 0,
                            StackSizeStarting = 0,
                            StartTime = new DateTime(2023, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Saeid's House"
                        },
                        new
                        {
                            TournamentId = 4,
                            AddOn = 0.0,
                            Bounty = 0.0,
                            BuyIn = 50.0,
                            EndTime = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LeagueId = 1,
                            MaxAddOnCount = 0,
                            MaxParticipants = 0,
                            Name = "Saeid #3 $50 No Limit Holdem",
                            Rebuy = 50.0,
                            StackSizeAddon = 0,
                            StackSizeRebuy = 0,
                            StackSizeStarting = 0,
                            StartTime = new DateTime(2023, 3, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Venue = "Saeid's House"
                        });
                });

            modelBuilder.Entity("PokerTournamentManager.Models.Participant", b =>
                {
                    b.HasOne("PokerTournamentManager.Models.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokerTournamentManager.Models.Tournament", "Tournament")
                        .WithMany("Participants")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("PokerTournamentManager.Models.Tournament", b =>
                {
                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
